[package]
name = "grpc-web-server"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A gRPC web proxy library and app written in Rust with a built in HTTP web server"

[workspace]
resolver = "3"
members = []

[lib]
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "grpc-web-server"
path = "./src/bin/grpc-web-server.rs"

[[bin]]
name = "gen-certs"
path = "./src/bin/gen-certs.rs"

[dependencies]
axum = "0.8.9"
axum-server = { version = "0.8.0", features = ["rustls", "tls-rustls"] }
clap = { version = "4.6.6", features = ["derive"] }
http = "1.5.0"
hyper = "1.11.0"
hyper-rustls = { version = "0.27.9", features = ["http2"] }
hyper-util = "0.1.20"
rcgen = "0.14.9"
rustls = "0.23.43"
rustls-pemfile = "2.2.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
tonic = "0.14.6"
tonic-web = "0.14.6"
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["fs", "cors", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
cbindgen = "0.29.4"
